name: Build and deploy Python app to Azure Web App - python-convert

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade pdf2docx  # If you specifically need to upgrade pdf2docx

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
          # Exclude venv directory as it should not be part of the deployment
          # Exclude files you don't need (e.g., venv)
          # You can add a `.gitignore` or exclude based on your needs
          # !venv/  # Uncomment this line if you wish to exclude venv

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6E779BFF62684E3D97CE6E0AEFDE900F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_288DA2A6C0744268BEF245BD130E46A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4EF2534F4AA4562BB1CA1B996453162 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'python-convert'
          slot-name: 'Production'
          
      - name: Confirm deployment
        run: |
          echo "App deployed to Azure Web App. URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
